# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/zeroflte/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/samsung/zeroflte/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

PRODUCT_COPY_FILES += \
	vendor/samsung/zeroflte/proprietary/bin/gps.cer:system/bin/gps.cer \
	vendor/samsung/zeroflte/proprietary/bin/gpsd:system/bin/gpsd \
	vendor/samsung/zeroflte/proprietary/etc/gps.conf:system/etc/gps.conf \
	vendor/samsung/zeroflte/proprietary/etc/gps.xml:system/etc/gps.xml \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/bcm4358A0_V0009.0033.hcd:system/vendor/firmware/bcm4358A0_V0009.0033.hcd \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/bcm4358A1_V0041.0075.hcd:system/vendor/firmware/bcm4358A1_V0041.0075.hcd \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/bcm4358A3_V0031.0048.hcd:system/vendor/firmware/bcm4358A3_V0031.0048.hcd \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/companion_2p2_master_setfile.bin:system/vendor/firmware/companion_2p2_master_setfile.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/companion_2p2_mode_setfile.bin:system/vendor/firmware/companion_2p2_mode_setfile.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/companion_fw_2p2_evt1.bin:system/vendor/firmware/companion_fw_2p2_evt1.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/companion_fw_imx240_evt1.bin:system/vendor/firmware/companion_fw_imx240_evt1.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/companion_imx240_master_setfile.bin:system/vendor/firmware/companion_imx240_master_setfile.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/companion_imx240_mode_setfile.bin:system/vendor/firmware/companion_imx240_mode_setfile.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/fimc_is_fw2_2p2.bin:system/vendor/firmware/fimc_is_fw2_2p2.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/fimc_is_fw2_imx240.bin:system/vendor/firmware/fimc_is_fw2_imx240.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/ois_fw_dom.bin:system/vendor/firmware/ois_fw_dom.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/ois_fw_sec.bin:system/vendor/firmware/ois_fw_sec.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/sec_s3fwrn5p_firmware.bin:system/vendor/firmware/sec_s3fwrn5p_firmware.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/seiren_fw_dram.bin:system/vendor/firmware/seiren_fw_dram.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/seiren_fw_sram.bin:system/vendor/firmware/seiren_fw_sram.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/setfile_2p2.bin:system/vendor/firmware/setfile_2p2.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/setfile_4e6.bin:system/vendor/firmware/setfile_4e6.bin \
	vendor/samsung/zeroflte/proprietary/vendor/firmware/setfile_imx240.bin:system/vendor/firmware/setfile_imx240.bin \
	vendor/samsung/zeroflte/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
	vendor/samsung/zeroflte/proprietary/vendor/lib/libOpenCL.so.1:system/vendor/lib/libOpenCL.so.1 \
	vendor/samsung/zeroflte/proprietary/vendor/lib/libOpenCL.so.1.1:system/vendor/lib/libOpenCL.so.1.1 \
	vendor/samsung/zeroflte/proprietary/vendor/lib/liblvverx_3.27.02.so:system/vendor/lib/liblvverx_3.27.02.so \
	vendor/samsung/zeroflte/proprietary/vendor/lib/liblvvetx_3.27.02.so:system/vendor/lib/liblvvetx_3.27.02.so \
	vendor/samsung/zeroflte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
	vendor/samsung/zeroflte/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwater-dsp3-tx-nb.bin:system/etc/firmware/clearwater-dsp3-tx-nb.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwater-dsp3-tx-swb-interview.bin:system/etc/firmware/clearwater-dsp3-tx-swb-interview.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwater-dsp3-tx-wb.bin:system/etc/firmware/clearwater-dsp3-tx-wb.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwater-dsp4-rx-anc-nb.bin:system/etc/firmware/clearwater-dsp4-rx-anc-nb.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwater-dsp4-rx-anc-wb.bin:system/etc/firmware/clearwater-dsp4-rx-anc-wb.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwater-dsp6-lpsd-control.bin:system/etc/firmware/clearwater-dsp6-lpsd-control.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp2-tx-nb.wmfw:system/etc/firmware/clearwatera-dsp2-tx-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp2-tx-swb.wmfw:system/etc/firmware/clearwatera-dsp2-tx-swb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp2-tx-wb.wmfw:system/etc/firmware/clearwatera-dsp2-tx-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp3-tx-nb.wmfw:system/etc/firmware/clearwatera-dsp3-tx-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp3-tx-swb.wmfw:system/etc/firmware/clearwatera-dsp3-tx-swb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp3-tx-wb.wmfw:system/etc/firmware/clearwatera-dsp3-tx-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp4-rx-anc-nb.wmfw:system/etc/firmware/clearwatera-dsp4-rx-anc-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp4-rx-anc-wb.wmfw:system/etc/firmware/clearwatera-dsp4-rx-anc-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp5-dsm.wmfw:system/etc/firmware/clearwatera-dsp5-dsm.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwatera-dsp6-ez2-control.wmfw:system/etc/firmware/clearwatera-dsp6-ez2-control.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp2-tx-nb.wmfw:system/etc/firmware/clearwaterc-dsp2-tx-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp2-tx-swb.wmfw:system/etc/firmware/clearwaterc-dsp2-tx-swb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp2-tx-wb.wmfw:system/etc/firmware/clearwaterc-dsp2-tx-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp3-tx-nb.wmfw:system/etc/firmware/clearwaterc-dsp3-tx-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp3-tx-swb.wmfw:system/etc/firmware/clearwaterc-dsp3-tx-swb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp3-tx-wb.wmfw:system/etc/firmware/clearwaterc-dsp3-tx-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp4-rx-anc-nb.wmfw:system/etc/firmware/clearwaterc-dsp4-rx-anc-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp4-rx-anc-wb.wmfw:system/etc/firmware/clearwaterc-dsp4-rx-anc-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp5-dsm.wmfw:system/etc/firmware/clearwaterc-dsp5-dsm.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/clearwaterc-dsp6-ez2-control.wmfw:system/etc/firmware/clearwaterc-dsp6-ez2-control.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp1-edac.bin:system/etc/firmware/florida-dsp1-edac.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp1-edac.wmfw:system/etc/firmware/florida-dsp1-edac.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp2-tx-fb-meeting.bin:system/etc/firmware/florida-dsp2-tx-fb-meeting.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp2-tx-fb-meeting.wmfw:system/etc/firmware/florida-dsp2-tx-fb-meeting.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp2-tx-nb.wmfw:system/etc/firmware/florida-dsp2-tx-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp2-tx-swb.wmfw:system/etc/firmware/florida-dsp2-tx-swb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp2-tx-wb.wmfw:system/etc/firmware/florida-dsp2-tx-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-ez2-control.wmfw:system/etc/firmware/florida-dsp3-ez2-control.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-lpsd-control.bin:system/etc/firmware/florida-dsp3-lpsd-control.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-nb.bin:system/etc/firmware/florida-dsp3-tx-nb.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-nb.wmfw:system/etc/firmware/florida-dsp3-tx-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-swb-conversation.bin:system/etc/firmware/florida-dsp3-tx-swb-conversation.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-swb-interview.bin:system/etc/firmware/florida-dsp3-tx-swb-interview.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-swb.wmfw:system/etc/firmware/florida-dsp3-tx-swb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-wb-meeting.bin:system/etc/firmware/florida-dsp3-tx-wb-meeting.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-wb-meeting.wmfw:system/etc/firmware/florida-dsp3-tx-wb-meeting.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-wb.bin:system/etc/firmware/florida-dsp3-tx-wb.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp3-tx-wb.wmfw:system/etc/firmware/florida-dsp3-tx-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp4-dsm.wmfw:system/etc/firmware/florida-dsp4-dsm.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.bin:system/etc/firmware/florida-dsp4-rx-anc-nb.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.wmfw:system/etc/firmware/florida-dsp4-rx-anc-nb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.bin:system/etc/firmware/florida-dsp4-rx-anc-wb.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.wmfw:system/etc/firmware/florida-dsp4-rx-anc-wb.wmfw \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_de_de_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_de_de_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_en_gb_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_en_gb_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_en_us_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_en_us_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_es_es_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_es_es_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_es_us_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_es_us_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_fr_fr_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_fr_fr_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_it_it_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_it_it_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_ja_jp_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_ja_jp_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_ko_kr_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_ko_kr_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_pt_br_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_pt_br_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_ru_ru_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_ru_ru_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_am_quiet_zh_cn_v2.bin:system/etc/firmware/samsung_wakeup_am_quiet_zh_cn_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_de_de_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_de_de_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_en_gb_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_en_gb_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_en_us_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_en_us_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_es_es_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_es_es_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_es_us_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_es_us_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_fr_fr_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_fr_fr_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_it_it_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_it_it_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_ja_jp_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_ja_jp_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_ko_kr_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_ko_kr_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_pt_br_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_pt_br_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_ru_ru_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_ru_ru_v2.bin \
	vendor/samsung/zeroflte/proprietary/etc/firmware/samsung_wakeup_grammar_quiet_zh_cn_v2.bin:system/etc/firmware/samsung_wakeup_grammar_quiet_zh_cn_v2.bin \
	vendor/samsung/zeroflte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
	vendor/samsung/zeroflte/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
	vendor/samsung/zeroflte/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
	vendor/samsung/zeroflte/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
	vendor/samsung/zeroflte/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
	vendor/samsung/zeroflte/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
	vendor/samsung/zeroflte/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
	vendor/samsung/zeroflte/proprietary/lib64/libexynoscamera.so:system/lib64/libexynoscamera.so \
	vendor/samsung/zeroflte/proprietary/lib64/libexynoscamera3.so:system/lib64/libexynoscamera3.so \
	vendor/samsung/zeroflte/proprietary/lib64/libexynosgscaler.so:system/lib64/libexynosgscaler.so \
	vendor/samsung/zeroflte/proprietary/lib64/libexynosscaler.so:system/lib64/libexynosscaler.so \
	vendor/samsung/zeroflte/proprietary/lib64/libexynosutils.so:system/lib64/libexynosutils.so \
	vendor/samsung/zeroflte/proprietary/lib64/libexynosv4l2.so:system/lib64/libexynosv4l2.so \
	vendor/samsung/zeroflte/proprietary/lib64/libion_exynos.so:system/lib64/libion_exynos.so
